removing double quote due to CSV export of stackoverflow data

diff --git a/data/stackoverflow-snippets/bash/132 b/data/stackoverflow-snippets/bash/132
--- a/data/stackoverflow-snippets/bash/132
+++ b/data/stackoverflow-snippets/bash/132
@@ -1,22 +1,22 @@
 #!/bin/bash
 
-srchpath=""${1:-.}""      ## search path (default .)
-daterng=""${2:-30}""      ## date range (default 30)
+srchpath="${1:-.}"      ## search path (default .)
+daterng="${2:-30}"      ## date range (default 30)
 
-test -d ""$srchpath"" || {    ## validate search path
-    printf ""error: path not found '%s'.\n"" ""$srchpath""
+test -d "$srchpath" || {    ## validate search path
+    printf "error: path not found '%s'.\n" "$srchpath"
     exit 1
 }
-test ""$daterng"" -eq ""$daterng"" 2>/dev/null || { ## validate range
-    printf ""error: non-integer range entered '%s'.\n"" ""$daternd""
+test "$daterng" -eq "$daterng" 2>/dev/null || { ## validate range
+    printf "error: non-integer range entered '%s'.\n" "$daternd"
     exit 1
 }
-d=$(date -d""5 days ago"" +%s)    ## get 5 days ago
+d=$(date -d"5 days ago" +%s)    ## get 5 days ago
 
 for ((i = 1; i <= daterng; i++)); do    ## loop over days in range
-    dt=""$(date -d@$((d - i * 86400)) +%Y%m%d)""  ## get date yyyymmdd
-    fn=""$dt.tar.gz""     ## form filename yyyymmdd.tar.gz
-    echo ""tar -czf $fn \$(find $srchpath -type f -name *$dt*)"" ## echo command
+    dt="$(date -d@$((d - i * 86400)) +%Y%m%d)"  ## get date yyyymmdd
+    fn="$dt.tar.gz"     ## form filename yyyymmdd.tar.gz
+    echo "tar -czf $fn \$(find $srchpath -type f -name *$dt*)" ## echo command
     ## recursively compress matching files (no spaces allowed in name)
-    tar -czf ""$fn"" $(find ""$srchpath"" -type f -name *""$dt""*) 2>/dev/null
+    tar -czf "$fn" $(find "$srchpath" -type f -name *"$dt"*) 2>/dev/null
 done
diff --git a/data/stackoverflow-snippets/bash/182 b/data/stackoverflow-snippets/bash/182
--- a/data/stackoverflow-snippets/bash/182
+++ b/data/stackoverflow-snippets/bash/182
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 case $BASH_VERSION in
-  ''|[1-3].*) echo ""ERROR: Bash 4.0 or newer required"" >&2; exit 1;;
+  ''|[1-3].*) echo "ERROR: Bash 4.0 or newer required" >&2; exit 1;;
 esac
 
 # Use of lowercase names here is deliberate -- POSIX specifies all-caps names for variables
@@ -12,11 +12,11 @@ my_dir=/home/shell
 # Using an associative array rather than a regular one allows O(1) lookup
 declare -A cntl_exception_list
 cntl_exception_list=(
-  [""${my_dir}/test4.cntl""]=1
-  [""${my_dir}/test5.cntl""]=1
+  ["${my_dir}/test4.cntl"]=1
+  ["${my_dir}/test5.cntl"]=1
 )
 
 while IFS= read -r -d '' file; do
   [[ ${cntl_exception_list[$file]} ]] && continue
-  rm -f -- ""$file""
-done < <(find ""$my_dir"" -type f -print0)
+  rm -f -- "$file"
+done < <(find "$my_dir" -type f -print0)
diff --git a/data/stackoverflow-snippets/bash/2 b/data/stackoverflow-snippets/bash/2
--- a/data/stackoverflow-snippets/bash/2
+++ b/data/stackoverflow-snippets/bash/2
@@ -1,10 +1,10 @@
  set -o pipefail
 
- ql_node_value=""$json"" ql_to=2500 ql_write_and_keep_open | nc localhost ""${ql_server_port}"" | while read response; do
-     echo ""response from server: $response"";
+ ql_node_value="$json" ql_to=2500 ql_write_and_keep_open | nc localhost "${ql_server_port}" | while read response; do
+     echo "response from server: $response";
      return 0;
-     if [[ ""$response"" == ""released"" ]]; then
-        echo ""quicklock: Lock was released."";
+     if [[ "$response" == "released" ]]; then
+        echo "quicklock: Lock was released.";
         return 0;
      fi
   done;
@@ -13,8 +13,8 @@
  set +o pipefail
 
  if [[ ${exit_code} -eq 0 ]]; then
-    echo ""quicklock: lock was released!"";
+    echo "quicklock: lock was released!";
  fi
 
- >&2 echo ""quicklock: could not release lock."";
+ >&2 echo "quicklock: could not release lock.";
  return 1;
diff --git a/data/stackoverflow-snippets/bash/26 b/data/stackoverflow-snippets/bash/26
--- a/data/stackoverflow-snippets/bash/26
+++ b/data/stackoverflow-snippets/bash/26
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 case $BASH_VERSION in
-  ''|[123].*) echo ""ERROR: This script requires bash 4.0 or newer"" >&2; exit 1;;
+  ''|[123].*) echo "ERROR: This script requires bash 4.0 or newer" >&2; exit 1;;
 esac
 
 input_file=${1:-test.txt}
@@ -9,16 +9,16 @@ input_file=${1:-test.txt}
 declare -A vars=( )
 
 {
-  read -r -a vals               # read first line into array ""vals""
-  read -r -a keys               # read second line into array ""keys""
-  for idx in ""${!keys[@]}""; do  # iterate over array indexes (starting at 0)
+  read -r -a vals               # read first line into array "vals"
+  read -r -a keys               # read second line into array "keys"
+  for idx in "${!keys[@]}"; do  # iterate over array indexes (starting at 0)
     key=${keys[$idx]}           # extract key at that index
     val=${vals[$idx]}           # extract value at that index
     vars[$key]=$val             # assign the value to the key inside the associative array
   done
-} < ""$input_file""
+} < "$input_file"
 
 # print for debugging
 declare -p vars >&2
 
-echo ""Value of variable a is ${vars[a]}""
+echo "Value of variable a is ${vars[a]}"
diff --git a/data/stackoverflow-snippets/bash/281 b/data/stackoverflow-snippets/bash/281
--- a/data/stackoverflow-snippets/bash/281
+++ b/data/stackoverflow-snippets/bash/281
@@ -1,10 +1,10 @@
 function ql_acquire_lock {
   set -e;
-  name=""${1:-$PWD}""  # the lock name is the first argument, if that is empty, then set the lockname to $PWD
-  mkdir -p ""$HOME/.quicklock/locks""
-  fle=$(echo ""${name}"" | tr ""/"" _)
-  qln=""$HOME/.quicklock/locks/${fle}.lock""
-  mkdir ""${qln}"" &> /dev/null || { echo ""${ql_magenta}quicklock: could not acquire lock with name '${qln}'${ql_no_color}.""; exit 1; }
-  export quicklock_name=""${qln}"";  # export the var *only if* above mkdir command succeeds
+  name="${1:-$PWD}"  # the lock name is the first argument, if that is empty, then set the lockname to $PWD
+  mkdir -p "$HOME/.quicklock/locks"
+  fle=$(echo "${name}" | tr "/" _)
+  qln="$HOME/.quicklock/locks/${fle}.lock"
+  mkdir "${qln}" &> /dev/null || { echo "${ql_magenta}quicklock: could not acquire lock with name '${qln}'${ql_no_color}."; exit 1; }
+  export quicklock_name="${qln}";  # export the var *only if* above mkdir command succeeds
   trap on_ql_trap EXIT;
 }
diff --git a/data/stackoverflow-snippets/bash/3 b/data/stackoverflow-snippets/bash/3
--- a/data/stackoverflow-snippets/bash/3
+++ b/data/stackoverflow-snippets/bash/3
@@ -1,17 +1,17 @@
 mappingsByClientID () {
-  (($# != 3)) && { echo ""Insufficient arguments"" >&2; exit 1; }
+  (($# != 3)) && { echo "Insufficient arguments" >&2; exit 1; }
   declare -n arr=$1    # for indirect assignment
   id=$2                # 1 to 5 
   file=${mapfiles[$3]} # 0 to 1
-  [[ -f ""$file"" ]] || { echo ""File '$file' does not exist"" >&2; exit 1; }
+  [[ -f "$file" ]] || { echo "File '$file' does not exist" >&2; exit 1; }
 
   # Note: the word boundary `\b` is not supported in ERE
   # See related posts below
   #
-  mapfile -t arr < <(sed -r ""s/.*${id}=\[([^]\]+).*/\1/; s/,/ /g"" ""$file"")
+  mapfile -t arr < <(sed -r "s/.*${id}=\[([^]\]+).*/\1/; s/,/ /g" "$file")
   if ((${#arr[@]} == 0)); then
-      echo ""Couldn't find mapping for id '$id' in file '$file'"" >&2
+      echo "Couldn't find mapping for id '$id' in file '$file'" >&2
       exit 1
   fi
-  echo ""${arr[@]}""
+  echo "${arr[@]}"
 }
diff --git a/data/stackoverflow-snippets/bash/301 b/data/stackoverflow-snippets/bash/301
--- a/data/stackoverflow-snippets/bash/301
+++ b/data/stackoverflow-snippets/bash/301
@@ -1,9 +1,9 @@
 #!/bin/bash
 
-fn=""${1:-/dev/stdin}""   ## read from file ""$1"" or stdin
+fn="${1:-/dev/stdin}"   ## read from file "$1" or stdin
 
-[ -r ""$fn"" ] || {       ## validate file readable
-    printf ""error: unable to read from filename or stdin\n"" >&2
+[ -r "$fn" ] || {       ## validate file readable
+    printf "error: unable to read from filename or stdin\n" >&2
     exit 1
 }
 
@@ -13,21 +13,21 @@ lastmn=
 declare -i cnt=0
 
 while IFS+=',' read -r dt tm s; do          ## read each csv
-    hr=""${tm:0:2}""                          ## get hour and minute
-    min=""${tm:3:2}""
-    if [ -n ""$lastdt"" ]; then               ## do we have a lastdt?
-        if [ ""$min"" != ""$lastmn"" ]; then    ## if lastmin not current
-            printf ""%s, %s:%s, %d\n"" ""$lastdt"" ""$lasthr"" ""$lastmn"" $cnt
+    hr="${tm:0:2}"                          ## get hour and minute
+    min="${tm:3:2}"
+    if [ -n "$lastdt" ]; then               ## do we have a lastdt?
+        if [ "$min" != "$lastmn" ]; then    ## if lastmin not current
+            printf "%s, %s:%s, %d\n" "$lastdt" "$lasthr" "$lastmn" $cnt
             cnt=0   ## reset count
         fi
     fi
 
-    lastdt=""$dt""    ## save last values
-    lasthr=""$hr""
-    lastmn=""$min""
+    lastdt="$dt"    ## save last values
+    lasthr="$hr"
+    lastmn="$min"
     ((cnt++))       ## increment count
 
-done < ""$fn""
+done < "$fn"
 
 ## output final session count
-printf ""%s, %s:%s, %d\n"" ""$lastdt"" ""$lasthr"" ""$lastmn"" $cnt
+printf "%s, %s:%s, %d\n" "$lastdt" "$lasthr" "$lastmn" $cnt
diff --git a/data/stackoverflow-snippets/bash/330 b/data/stackoverflow-snippets/bash/330
--- a/data/stackoverflow-snippets/bash/330
+++ b/data/stackoverflow-snippets/bash/330
@@ -6,7 +6,7 @@
 #CP works differently, provided that d in /c/d isn't an existing file, it assumes that you're copying item into a folder path called /c/d and will create it if it doesn't exist. so CP /a/b /c/d will always give /c/d/b unless d is an existing file. If you put the --rename switch, it will assume that you're copying into /c and renaming the singl item you're copying from b to d at the destination. Again, if /c doesn't exist, it will be created. So CP --rename /a/b /c/d will give a /c/d and if there already a folder called /c/d, contents of b will be merged into d. 
 
 #cp+ $source $destination
-#mkdir -p /foo/bar && cp myfile ""$_""
+#mkdir -p /foo/bar && cp myfile "$_"
 
 err=0 # error count
 i=0 #item counter, doesn't include destination (starts at 1, ex. item1, item2 etc)
@@ -15,10 +15,10 @@ n=1 # argument counter (aka the arguments inputed into script, those include bot
 count_s=0
 count_i=0
 easy_going=true #determines how you deal with bad pathes in your copy, true will allow copy to continue provided one of the items being copied exists, false will exit script for one bad path. this setting can also be changed via the custom switches: --strict and --not-strict
-verbal=""-v""
+verbal="-v"
 
 
-  help=""===============================================================================\
+  help="===============================================================================\
     \n         CREATIVE COPY SCRIPT (CP) -- written by thebunnyrules\
     \n===============================================================================\n
     \n This script (CP, note capital letters) is intended to supplement \
@@ -28,13 +28,13 @@ verbal=""-v""
     \n To make this happen, CP assumes that the item you're copying is \
     \n being dropped in the destination path and is not the destination\
     \n itself (aka, a renamed copy of the source file/folder). Meaning:\n 
-    \n * \""CP /a/b /c/d\"" will result in /c/d/b \
-    \n * even if you write \""CP /a/b /c/b\"", CP will create the path /a/b, \
+    \n * \"CP /a/b /c/d\" will result in /c/d/b \
+    \n * even if you write \"CP /a/b /c/b\", CP will create the path /a/b, \
     \n   resulting in /c/b/b. \n
     \n Of course, if /c/b or /c/d are existing files and /a/b is also a\
     \n file, the existing destination file will simply be overwritten. \
-    \n This behavior can be changed with the \""--rename\"" switch. In this\
-    \n case, it's assumed that \""CP --rename /a/b /c/d\"" is copying b into /c  \
+    \n This behavior can be changed with the \"--rename\" switch. In this\
+    \n case, it's assumed that \"CP --rename /a/b /c/d\" is copying b into /c  \
     \n and renaming the copy to d.\n
     \n===============================================================================\
     \n        CP specific help: Switches and their Usages \
@@ -51,49 +51,49 @@ verbal=""-v""
     \n\t\tmake strict the default behavior by editing the \
     \n\t\tCP script and setting: \n
     \n\t\teasy_going=false.\n
-    \n  --help-all\tShows help specific to cp (in addition to CP).""
+    \n  --help-all\tShows help specific to cp (in addition to CP)."
 
-cp_hlp=""\n\nRegular cp command's switches will still work when using CP.\
+cp_hlp="\n\nRegular cp command's switches will still work when using CP.\
     \nHere is the help out of the original cp command... \
     \n\n===============================================================================\
     \n          cp specific help: \
-    \n===============================================================================\n""
+    \n===============================================================================\n"
 
-outro1=""\n******************************************************************************\
+outro1="\n******************************************************************************\
     \n******************************************************************************\
     \n******************************************************************************\
     \n        USE THIS SCRIPT WITH CARE, TYPOS WILL GIVE YOU PROBLEMS...\
     \n******************************************************************************\
     \n******************************* HIT q TO EXIT ********************************\
-    \n******************************************************************************""
+    \n******************************************************************************"
 
 
 #count and classify arguments that were inputed into script, output help message if needed
 while true; do
-    eval input=""\$$n""
+    eval input="\$$n"
     in_=${input::1}
 
-    if [ -z ""$input"" -a $n = 1 ]; then input=""--help""; fi 
+    if [ -z "$input" -a $n = 1 ]; then input="--help"; fi 
 
-    if [ ""$input"" = ""-h"" -o ""$input"" = ""--help"" -o ""$input"" = ""-?"" -o ""$input"" = ""--help-all"" ]; then
-        if [ ""$input"" = ""--help-all"" ]; then 
-            echo -e ""$help""$cp_hlp > /tmp/cp.hlp 
+    if [ "$input" = "-h" -o "$input" = "--help" -o "$input" = "-?" -o "$input" = "--help-all" ]; then
+        if [ "$input" = "--help-all" ]; then 
+            echo -e "$help"$cp_hlp > /tmp/cp.hlp 
             cp --help >> /tmp/cp.hlp
-            echo -e ""$outro1"" >> /tmp/cp.hlp
+            echo -e "$outro1" >> /tmp/cp.hlp
             cat /tmp/cp.hlp|less
             cat /tmp/cp.hlp
             rm /tmp/cp.hlp
         else
-            echo -e ""$help"" ""$outro1""|less
-            echo -e ""$help"" ""$outro1""
+            echo -e "$help" "$outro1"|less
+            echo -e "$help" "$outro1"
         fi
         exit
     fi
 
-    if [ -z ""$input"" ]; then
+    if [ -z "$input" ]; then
         count_i=$(expr $count_i - 1 ) # remember, last item is destination and it's not included in cound
         break 
-    elif [ ""$in_"" = ""-"" ]; then
+    elif [ "$in_" = "-" ]; then
         count_s=$(expr $count_s + 1 )
     else
         count_i=$(expr $count_i + 1 )
@@ -103,40 +103,40 @@ done
 
 #error condition: no items to copy or no destination
     if [ $count_i -lt 0 ]; then 
-            echo ""Error: You haven't listed any items for copying. Exiting."" # you didn't put any items for copying
+            echo "Error: You haven't listed any items for copying. Exiting." # you didn't put any items for copying
     elif [ $count_i -lt 1 ]; then
-            echo ""Error: Copying usually involves a destination. Exiting."" # you put one item and no destination
+            echo "Error: Copying usually involves a destination. Exiting." # you put one item and no destination
     fi
 
 #reset the counter and grab content of arguments, aka: switches and item paths
 n=1
 while true; do
-        eval input=""\$$n"" #input=$1,$2,$3,etc...
+        eval input="\$$n" #input=$1,$2,$3,etc...
         in_=${input::1} #first letter of $input
 
-        if [ ""$in_"" = ""-"" ]; then
-            if [ ""$input"" = ""--rename"" ]; then 
+        if [ "$in_" = "-" ]; then
+            if [ "$input" = "--rename" ]; then 
                 rename=true #my custom switches
-            elif [ ""$input"" = ""--strict"" ]; then 
+            elif [ "$input" = "--strict" ]; then 
                 easy_going=false #exit script if even one of the non-destinations item is not found
-            elif [ ""$input"" = ""--relaxed"" ]; then 
+            elif [ "$input" = "--relaxed" ]; then 
                 easy_going=true #continue script if at least one of the non-destination items is found
-            elif [ ""$input"" = ""--quiet"" ]; then 
-                verbal=""""
+            elif [ "$input" = "--quiet" ]; then 
+                verbal=""
             else
-                #m=$(expr $m + 1);eval switch$m=""$input"" #input is a switch, if it's not one of the above, assume it belongs to cp.
-                switch_list=""$switch_list \""$input\""""
+                #m=$(expr $m + 1);eval switch$m="$input" #input is a switch, if it's not one of the above, assume it belongs to cp.
+                switch_list="$switch_list \"$input\""
             fi                                  
-        elif ! [ -z ""$input"" ]; then #if it's not a switch and input is not empty, it's a path
+        elif ! [ -z "$input" ]; then #if it's not a switch and input is not empty, it's a path
                 i=$(expr $i + 1)
-                if [ ! -f ""$input"" -a ! -d ""$input"" -a ""$i"" -le ""$count_i"" ]; then 
-                    err=$(expr $err + 1 ); error_list=""$error_list\npath does not exit: \""b\""""
+                if [ ! -f "$input" -a ! -d "$input" -a "$i" -le "$count_i" ]; then 
+                    err=$(expr $err + 1 ); error_list="$error_list\npath does not exit: \"b\""
                 else
-                    if [ ""$i"" -le ""$count_i"" ]; then 
-                        eval item$i=""$input"" 
-                        item_list=""$item_list \""$input\""""
+                    if [ "$i" -le "$count_i" ]; then 
+                        eval item$i="$input" 
+                        item_list="$item_list \"$input\""
                     else
-                        destination=""$input"" #destination is last items entered
+                        destination="$input" #destination is last items entered
                     fi
                 fi
         else
@@ -149,16 +149,16 @@ while true; do
 done
 
 #error condition: some or all item(s) being copied don't exist. easy_going: continue if at least one item exists, warn about rest, not easy_going: exit.
-#echo ""err=$err count_i=$count_i""
-if [ ""$easy_going"" != true -a $err -gt 0 -a $err != $count_i ]; then 
-    echo ""Some of the paths you entered are incorrect. Script is running in strict mode and will therefore exit.""
-    echo -e ""Bad Paths: $err $error_list""
+#echo "err=$err count_i=$count_i"
+if [ "$easy_going" != true -a $err -gt 0 -a $err != $count_i ]; then 
+    echo "Some of the paths you entered are incorrect. Script is running in strict mode and will therefore exit."
+    echo -e "Bad Paths: $err $error_list"
     exit
 fi
 
 if [ $err = $count_i ]; then
-    echo ""ALL THE PATHS you have entered are incorrect! Exiting.""
-    echo -e ""Bad Paths: $err $error_list""
+    echo "ALL THE PATHS you have entered are incorrect! Exiting."
+    echo -e "Bad Paths: $err $error_list"
 fi
 
 #one item to one destination:
@@ -176,43 +176,43 @@ fi
 # - rename option but source is folder, destination is file, exit.
 # - rename option but source is file and destination is folder. easy_going: option ignored.
 
-if [ -f ""$destination"" ]; then
+if [ -f "$destination" ]; then
     if [ $count_i -gt 1 ]; then 
-        echo ""Error: You've selected a single file as a destination and are copying multiple items to it. Exiting.""; exit
-    elif [ -d ""$item1"" ]; then
-        echo ""Error: Your destination is a file but your source is a folder. Exiting.""; exit
+        echo "Error: You've selected a single file as a destination and are copying multiple items to it. Exiting."; exit
+    elif [ -d "$item1" ]; then
+        echo "Error: Your destination is a file but your source is a folder. Exiting."; exit
     fi
 fi
-if [ ""$rename"" = true ]; then
+if [ "$rename" = true ]; then
     if [ $count_i -gt 1 ]; then
         if [ $easy_going = true ]; then
-            echo ""Warning: you choose the rename option but are copying multiple items. Ignoring Rename option. Continuing.""
+            echo "Warning: you choose the rename option but are copying multiple items. Ignoring Rename option. Continuing."
         else
-            echo ""Error: you choose the rename option but are copying multiple items. Script running in strict mode. Exiting.""; exit
+            echo "Error: you choose the rename option but are copying multiple items. Script running in strict mode. Exiting."; exit
         fi
-    elif [ -d ""$destination"" -a -f ""$item1"" ]; then
-        echo -n ""Warning: you choose the rename option but source is a file and destination is a folder with the same name. ""
+    elif [ -d "$destination" -a -f "$item1" ]; then
+        echo -n "Warning: you choose the rename option but source is a file and destination is a folder with the same name. "
         if [ $easy_going = true ]; then
-            echo ""Ignoring Rename option. Continuing.""
+            echo "Ignoring Rename option. Continuing."
         else
-            echo ""Script running in strict mode. Exiting.""; exit
+            echo "Script running in strict mode. Exiting."; exit
         fi
     else
-        dest_jr=$(dirname ""$destination"")
-        if [ -d ""$destination"" ]; then item_list=""$item1/*"";fi
-        mkdir -p ""$dest_jr""
+        dest_jr=$(dirname "$destination")
+        if [ -d "$destination" ]; then item_list="$item1/*";fi
+        mkdir -p "$dest_jr"
     fi
 else
-    mkdir -p ""$destination""
+    mkdir -p "$destination"
 fi
 
-eval cp $switch_list $verbal $item_list ""$destination""
+eval cp $switch_list $verbal $item_list "$destination"
 
-cp_err=""$?""
-if [ ""$cp_err"" != 0 ]; then 
-    echo -e ""Something went wrong with the copy operation. \nExit Status: $cp_err""
+cp_err="$?"
+if [ "$cp_err" != 0 ]; then 
+    echo -e "Something went wrong with the copy operation. \nExit Status: $cp_err"
 else 
-    echo ""Copy operation exited with no errors.""
+    echo "Copy operation exited with no errors."
 fi
 
 exit
diff --git a/data/stackoverflow-snippets/bash/332 b/data/stackoverflow-snippets/bash/332
--- a/data/stackoverflow-snippets/bash/332
+++ b/data/stackoverflow-snippets/bash/332
@@ -1,24 +1,24 @@
 #!/bin/sh
 
-if [ -z ""$1"" ]; then
-  echo ""I'd love me an option."" >&2
+if [ -z "$1" ]; then
+  echo "I'd love me an option." >&2
   exit 1
 fi
 
 OK=1
 CRITICAL=0
 
-x=""${1#?}""                 # make a temporary string missing the 1st chararcter,
-re=""[${1%$x}]$x""           # then place the 1st character within square brackets.
+x="${1#?}"                 # make a temporary string missing the 1st chararcter,
+re="[${1%$x}]$x"           # then place the 1st character within square brackets.
 
-PROC_COUNT=$( ps -ef | grep -w -c ""$re"" )       # yay, just one pipe.
+PROC_COUNT=$( ps -ef | grep -w -c "$re" )       # yay, just one pipe.
 
-if [ ""$PROC_COUNT"" -eq ""$OK"" ]; then
-  echo ""OK""
-elif [ ""$PROC_COUNT"" -eq ""$CRITICAL"" ]; then
-  echo ""CRITICAL""
-elif [ ""$PROC_COUNT"" -gt ""$OK"" ]; then
-  echo ""MULTIPLE process are running""
+if [ "$PROC_COUNT" -eq "$OK" ]; then
+  echo "OK"
+elif [ "$PROC_COUNT" -eq "$CRITICAL" ]; then
+  echo "CRITICAL"
+elif [ "$PROC_COUNT" -gt "$OK" ]; then
+  echo "MULTIPLE process are running"
 else
-  echo ""error""
+  echo "error"
 fi
diff --git a/data/stackoverflow-snippets/bash/346 b/data/stackoverflow-snippets/bash/346
--- a/data/stackoverflow-snippets/bash/346
+++ b/data/stackoverflow-snippets/bash/346
@@ -33,28 +33,28 @@ get_key_path() {
 }
 
 get_password() {
-    if [ ! -x ""$(command -v openssl)"" ]; then
-        echo ""Error: OpenSSL is not installed or not accessible in the current path.  Please install it and try again."" >&2
+    if [ ! -x "$(command -v openssl)" ]; then
+        echo "Error: OpenSSL is not installed or not accessible in the current path.  Please install it and try again." >&2
         exit 1
     fi
 
     KEY_PATH=$(get_key_path $1)
 
     if [ ! -d $KEY_PATH ]; then
-        echo ""Error: KEY_PATH directory $KEY_PATH not found.  Please check permissions and try again."" >&2
+        echo "Error: KEY_PATH directory $KEY_PATH not found.  Please check permissions and try again." >&2
         exit 1
     fi
 
     # Create a PKCS8 version of the public key in the current directory if one does not already exist
     if [ ! -z id_rsa.pub.pem ]; then
-        if [ ! -x ""$(command -v ssh-keygen)"" ]; then
-            echo ""ssh-keygen is needed to generate a PKCS8 version of your public key.  Please install it and try again."" >&2
+        if [ ! -x "$(command -v ssh-keygen)" ]; then
+            echo "ssh-keygen is needed to generate a PKCS8 version of your public key.  Please install it and try again." >&2
         fi
 
         ssh-keygen -f $KEY_PATH/id_rsa.pub -e -m PKCS8 > id_rsa.pub.pem
 
         if [ ! -f id_rsa.pub.pem ]; then
-            echo ""Failed to create PKCS8 version of the public key.  Please check permissions and try again."" >&2
+            echo "Failed to create PKCS8 version of the public key.  Please check permissions and try again." >&2
             exit 1
         fi
     fi
@@ -67,18 +67,18 @@ get_password() {
 }
 
 set_password() {
-    echo ""Enter your Password:"" >&2
+    echo "Enter your Password:" >&2
     stty -echo
     read PASSWORD
     stty echo
-    echo ""Confirm your Password:"" >&2
+    echo "Confirm your Password:" >&2
     stty -echo
     read CPASSWORD
     stty echo
     if [ $PASSWORD == $CPASSWORD ]; then
         echo $PASSWORD | openssl rsautl -encrypt -pubin -inkey id_rsa.pub.pem -out pass.enc
     else
-        echo ""Error: passwords do not match.  Please try again."" >&2
+        echo "Error: passwords do not match.  Please try again." >&2
         exit 1
     fi
 }
@@ -86,11 +86,11 @@ set_password() {
 get_abs_filename() {
   # $1 : relative filename
   filename=$1
-  parentdir=$(dirname ""${filename}"")
+  parentdir=$(dirname "${filename}")
 
-  if [ -d ""${filename}"" ]; then
-      echo ""$(cd ""${filename}"" && pwd)""
-  elif [ -d ""${parentdir}"" ]; then
-    echo ""$(cd ""${parentdir}"" && pwd)/$(basename ""${filename}"")""
+  if [ -d "${filename}" ]; then
+      echo "$(cd "${filename}" && pwd)"
+  elif [ -d "${parentdir}" ]; then
+    echo "$(cd "${parentdir}" && pwd)/$(basename "${filename}")"
   fi
 }
diff --git a/data/stackoverflow-snippets/bash/384 b/data/stackoverflow-snippets/bash/384
--- a/data/stackoverflow-snippets/bash/384
+++ b/data/stackoverflow-snippets/bash/384
@@ -4,12 +4,12 @@ main()
 {
    set -x
    local BIN_PATH CertType Password Commonname 
-   BIN_PATH=""keytool""
+   BIN_PATH="keytool"
    # add commas between the long options
-   if ! options=$(getopt -u -o t:p:c: -l certtype:,password:,commonname: -- ""$@"")
+   if ! options=$(getopt -u -o t:p:c: -l certtype:,password:,commonname: -- "$@")
       then
       # something went wrong, getopt will put out an error message for us
-         echo ""Error on parsing parameters""
+         echo "Error on parsing parameters"
          exit 1
    fi  
 
@@ -17,20 +17,20 @@ main()
 
    while [ $# -gt 0 ] 
    do
-      case ""$1"" in
-       -t | --certtype) CertType=""$2"" ; shift;;
-       -p | --password) Password=""$2"" ; shift;;
-       -c | --commonname) Commonname=""$2"" ;shift;;
+      case "$1" in
+       -t | --certtype) CertType="$2" ; shift;;
+       -p | --password) Password="$2" ; shift;;
+       -c | --commonname) Commonname="$2" ;shift;;
        -- ) shift; break;;
-       -* ) echo ""$0: error - unrecognized option $1"" 1>&2; exit 1;; 
+       -* ) echo "$0: error - unrecognized option $1" 1>&2; exit 1;; 
        *  ) break;;
       esac
       shift
    done
 
-   echo ""Cert type is: $CertType""
+   echo "Cert type is: $CertType"
    # correct the two variable names below
-   echo ""Password is: $Password""        # was $KeystorePassword
-   echo ""common name is: $Commonname""   # was $CommonName
+   echo "Password is: $Password"        # was $KeystorePassword
+   echo "common name is: $Commonname"   # was $CommonName
 }
-main ""$@""
+main "$@"
diff --git a/data/stackoverflow-snippets/bash/414 b/data/stackoverflow-snippets/bash/414
--- a/data/stackoverflow-snippets/bash/414
+++ b/data/stackoverflow-snippets/bash/414
@@ -1,22 +1,22 @@
 #!/bin/bash
 
-[ -n ""$1"" ] || {    ## validate one argument given
-    printf ""error: insufficient input\nusage: %s dd-mmm-yy hh.mm.ss.ms\n"" \
-    ""${0##*/}""
+[ -n "$1" ] || {    ## validate one argument given
+    printf "error: insufficient input\nusage: %s dd-mmm-yy hh.mm.ss.ms\n" \
+    "${0##*/}"
     exit 1
 }
 
-oifs=""$IFS""         ## save original Internal Field Separator
+oifs="$IFS"         ## save original Internal Field Separator
 IFS=$' \t\n-.';     ## set IFS to break on - or .
 
 dt=( $(echo $1) )   ## separate date into indexed array
 
-[ ""${#dt[@]}"" -lt '7' ] && {    ## check all 7 components present
-    printf ""error: date doesn't match dd-mmm-yy hh.mm.ss.ms format\n""
+[ "${#dt[@]}" -lt '7' ] && {    ## check all 7 components present
+    printf "error: date doesn't match dd-mmm-yy hh.mm.ss.ms format\n"
     exit 1
 }
 
-IFS=""$oifs""         ## reset original IFS
+IFS="$oifs"         ## reset original IFS
 
 ## create associative array mapping months to numerics
 declare -A mo=(
@@ -35,15 +35,15 @@ declare -A mo=(
 )
 
 ## any date after 30 considerd 1930, else considered 2000
-[ ""${dt[2]}"" -gt '30' ] && dt[2]=$((${dt[2]} + 1000)) || \
+[ "${dt[2]}" -gt '30' ] && dt[2]=$((${dt[2]} + 1000)) || \
 dt[2]=$((${dt[2]} + 2000))
 
 ## use date to convert array contents to seconds since epoch
-epochsec=$( date -d ""${dt[2]}-${mo[${dt[1]}]}-${dt[0]} \
-                    ${dt[3]}:${dt[4]}:${dt[5]}.${dt[6]}"" +%s )
+epochsec=$( date -d "${dt[2]}-${mo[${dt[1]}]}-${dt[0]} \
+                    ${dt[3]}:${dt[4]}:${dt[5]}.${dt[6]}" +%s )
 
-if [ ""$?"" -ne '0' ]; then   ## check if last return was error
-    printf ""error: invalid date.\n""
+if [ "$?" -ne '0' ]; then   ## check if last return was error
+    printf "error: invalid date.\n"
 else    ## output good date
-    printf ""date: %s\n"" ""$(date -d @$epochsec)""
+    printf "date: %s\n" "$(date -d @$epochsec)"
 fi
diff --git a/data/stackoverflow-snippets/bash/604 b/data/stackoverflow-snippets/bash/604
--- a/data/stackoverflow-snippets/bash/604
+++ b/data/stackoverflow-snippets/bash/604
@@ -1,6 +1,6 @@
 #!/bin/bash
 # Checking pre-requirements, the script should contain one argument
-[ -z ""$1"" ] && echo ""Usage : script user_name"" && exit 1
+[ -z "$1" ] && echo "Usage : script user_name" && exit 1
 username=$1
 # Read password key and has silently using -s ie keystrokes are invisible
 read -sp 'Enter password key - ' key
@@ -11,7 +11,7 @@ read -sp 'Enter password key - ' key
 read -sp 'Read upto 8 characters for salt - ' salt
 # You can sanitize the user input for salt to trim its length to 8 and use it like below
 useradd -m -d /home/$username \
--p $(perl -e 'print crypt(""$ARGV[0]"", ""\$1\$$ARGV[1]"")' ""$username"" ""${salt:0:8}"")
+-p $(perl -e 'print crypt("$ARGV[0]", "\$1\$$ARGV[1]")' "$username" "${salt:0:8}")
 # Check the exit status of the last command
-[ $? -eq 0 ] && echo ""User $username successfully created"" || \
-echo ""Sorry ! User $username couldn't be created at the moment""
+[ $? -eq 0 ] && echo "User $username successfully created" || \
+echo "Sorry ! User $username couldn't be created at the moment"
diff --git a/data/stackoverflow-snippets/bash/631 b/data/stackoverflow-snippets/bash/631
--- a/data/stackoverflow-snippets/bash/631
+++ b/data/stackoverflow-snippets/bash/631
@@ -4,8 +4,8 @@ set -e
 
 if [ $# -lt 1 ] ; then
     # >&2 sends diagnostics to standard error
-    echo ""Usage: $0 [<Serial#> | <Socket#>] "" >&2
-    echo ""      Example:  $0 GESC637005W1 "" >&2
+    echo "Usage: $0 [<Serial#> | <Socket#>] " >&2
+    echo "      Example:  $0 GESC637005W1 " >&2
     exit 1
 fi
 
@@ -14,20 +14,20 @@ die () {
     rc=$1
     shift
     # include $0 in all diagnostic messages
-    echo ""$0: $@"" >&2
-    exit ""$rc""
+    echo "$0: $@" >&2
+    exit "$rc"
 }
 
-_socket=""$(/opt/Allure/socketdata ""$1"" |awk -F '[(/: ]'+ '{print $10}')""
-[ $_socket = ""400"" ] || die 200 ""Serial number $1 not found (socket $_socket)""
+_socket="$(/opt/Allure/socketdata "$1" |awk -F '[(/: ]'+ '{print $10}')"
+[ $_socket = "400" ] || die 200 "Serial number $1 not found (socket $_socket)"
 
 # Create a temporary file for this script
 t=$(mktemp -t screenshot.XXXXXXXXXX) || exit
 # Remove the temporary file on regular or error exit or signal
 trap 'rm -f $t' EXIT ERROR HUP INT TERM
 
-scp -P$_socket support@localhost:/srv/samba/share/clarity-client/client-apps/digital-poster/screens/screenshot.png ""$t"" ||
-die 201 ""401 scp1 failed $?""
+scp -P$_socket support@localhost:/srv/samba/share/clarity-client/client-apps/digital-poster/screens/screenshot.png "$t" ||
+die 201 "401 scp1 failed $?"
 
-scp ""$t"" support@172.24.16.37:/opt/digital_media/dm_content/screenshots/""$1"".png ||
-die 202 ""402 scp2 failed $?""
+scp "$t" support@172.24.16.37:/opt/digital_media/dm_content/screenshots/"$1".png ||
+die 202 "402 scp2 failed $?"
diff --git a/data/stackoverflow-snippets/bash/678 b/data/stackoverflow-snippets/bash/678
--- a/data/stackoverflow-snippets/bash/678
+++ b/data/stackoverflow-snippets/bash/678
@@ -1,22 +1,22 @@
 #!/bin/bash
 
 function die {
-    echo ""$1"" >&2
+    echo "$1" >&2
     exit -1
 }
 
-(( $# == 2 )) || die ""Usage: $0 <moved filename> <original filename>""
-[[ -e ""$1"" ]]  || die ""Not an existing file: $1""
-[[ ! -e ""$2"" ]] || die ""Not a missing file: $2""
+(( $# == 2 )) || die "Usage: $0 <moved filename> <original filename>"
+[[ -e "$1" ]]  || die "Not an existing file: $1"
+[[ ! -e "$2" ]] || die "Not a missing file: $2"
 
-hg_st_lines_1=$(hg st ""$1"" 2>/dev/null | wc -l)
-hg_st_lines_2=$(hg st ""$2"" 2>/dev/null | wc -l)
+hg_st_lines_1=$(hg st "$1" 2>/dev/null | wc -l)
+hg_st_lines_2=$(hg st "$2" 2>/dev/null | wc -l)
 
-(( ${hg_st_lines_1} == 1 )) || die ""Expected exactly one line in hg status for $1, but got ${hg_st_lines_1}""
-(( ${hg_st_lines_2} == 1 )) || die ""Expected exactly one line in hg status for $2, but got ${hg_st_lines_2}""
+(( ${hg_st_lines_1} == 1 )) || die "Expected exactly one line in hg status for $1, but got ${hg_st_lines_1}"
+(( ${hg_st_lines_2} == 1 )) || die "Expected exactly one line in hg status for $2, but got ${hg_st_lines_2}"
 
-[[ ""$(hg st ""$1"" 2>/dev/null)"" == \?* ]] || die ""Mercurial does not consider $1 to be an unknown (untracked) file""
-[[ ""$(hg st ""$2"" 2>/dev/null)"" =~ !.* ]] || die ""Mercurial does not consider $2 to be a missing file""
+[[ "$(hg st "$1" 2>/dev/null)" == \?* ]] || die "Mercurial does not consider $1 to be an unknown (untracked) file"
+[[ "$(hg st "$2" 2>/dev/null)" =~ !.* ]] || die "Mercurial does not consider $2 to be a missing file"
 
 mv $1 $2
 hg mv $2 $1
diff --git a/data/stackoverflow-snippets/bash/696 b/data/stackoverflow-snippets/bash/696
--- a/data/stackoverflow-snippets/bash/696
+++ b/data/stackoverflow-snippets/bash/696
@@ -1,33 +1,33 @@
-case ""$1"" in
-'' ) echo 1>&2 ""$0: Expecting two arguments that use alphabetic characters. Found: $# arguments, which was or were ($*)""
-    echo 1>&2 ""Usage: $0 Username-prefix GECOS/Description (Cannot use blank arguments)"" ;;
-*[![:alpha:]]* ) echo 1>&2 ""$0: Expecting two arguments that use only letters. Found: $# arguments, which was or were ($*)""
-    echo 1>&2 ""Usage: $0 Username-prefix GECOS/Description (No numbers, spaces, or special characters)"" ;;
+case "$1" in
+'' ) echo 1>&2 "$0: Expecting two arguments that use alphabetic characters. Found: $# arguments, which was or were ($*)"
+    echo 1>&2 "Usage: $0 Username-prefix GECOS/Description (Cannot use blank arguments)" ;;
+*[![:alpha:]]* ) echo 1>&2 "$0: Expecting two arguments that use only letters. Found: $# arguments, which was or were ($*)"
+    echo 1>&2 "Usage: $0 Username-prefix GECOS/Description (No numbers, spaces, or special characters)" ;;
 * ) prefix=$1  ;;
 esac
 
 #This case statement checks to ensure that all arguments passed to the command line are letters only and contain no special characters or blank arguments
 
-case ""$2"" in
-'' ) echo 1>&2 ""$0: Expecting two arguments that use alphabetic characters. Found: $# arguments, which was or were ($*)""
-    echo 1>&2 ""Usage: $0 Username-prefix GECOS/Description (Cannot use blank arguments)"" ;;
-*[![:alpha:]]* ) echo 1>&2 ""$0: Expecting two arguments that use only letters. Found: $# arguments, which was or were ($*)""
-    echo 1>&2 ""Usage: $0 Username-prefix GECOS/Description (No numbers, spaces, or special characters)"" ;;
+case "$2" in
+'' ) echo 1>&2 "$0: Expecting two arguments that use alphabetic characters. Found: $# arguments, which was or were ($*)"
+    echo 1>&2 "Usage: $0 Username-prefix GECOS/Description (Cannot use blank arguments)" ;;
+*[![:alpha:]]* ) echo 1>&2 "$0: Expecting two arguments that use only letters. Found: $# arguments, which was or were ($*)"
+    echo 1>&2 "Usage: $0 Username-prefix GECOS/Description (No numbers, spaces, or special characters)" ;;
 * ) geco=$2 ;;
 esac
 
 num=1
-user=$prefix""user""
+user=$prefix"user"
 uid=1001
 gid=$uid
 home=/home/$user
 shell=/bin/bash
 
-#echo ""pw_name:pw_passwd:pw_uid:pw_gid:pw_gecos:pw_dir:pw_shell""
+#echo "pw_name:pw_passwd:pw_uid:pw_gid:pw_gecos:pw_dir:pw_shell"
 #PASSWD=$(openssl rand -base64 12)
 
 for (( num=1; num<=30; num++ )) ; do
-    echo ""$user$(printf ""%02d\n"" $num):$(openssl rand -base64 12):$uid:$gid:$geco:$home$(printf ""%02d\n"" $num):$shell""
+    echo "$user$(printf "%02d\n" $num):$(openssl rand -base64 12):$uid:$gid:$geco:$home$(printf "%02d\n" $num):$shell"
     uid=$(( uid + 1 ))
     gid=$(( gid + 1 ))
 done
diff --git a/data/stackoverflow-snippets/bash/706 b/data/stackoverflow-snippets/bash/706
--- a/data/stackoverflow-snippets/bash/706
+++ b/data/stackoverflow-snippets/bash/706
@@ -1,45 +1,45 @@
 function get_mimetype(){
-  file --mime-type ""$1"" | sed 's/.*: //'
+  file --mime-type "$1" | sed 's/.*: //'
 }
 declare -a attachments
-attachments=(""A_PTDIFF.CVS"" ""A_PTMISS.CVS"" ""A_PTNPOS.CVS"" ""A_PTRCON.CVS"")
+attachments=("A_PTDIFF.CVS" "A_PTMISS.CVS" "A_PTNPOS.CVS" "A_PTRCON.CVS")
 
 {
-  boundary=""--random$$string--""
+  boundary="--random$$string--"
   # You were missing a space after '%s\n'
   # Also, I'm breaking this into multiple arguments for legibility
   printf '%s\n' \
-          ""From: jrpng"" \
-          ""To: tom@gmail.com"" \
-          ""Subject: Test new Bash script"" \
-          ""Mime-Version: 1.0"" \
-          ""Content-Type: multipart/mixed; boundary=\""$boundary\"""" \
-          ""X-Comment: # notice the empty line after this one"" \
-          """" \
-          ""--${boundary}"" \
-          ""Content-Type: text/plain; charset=\""US-ASCII\"""" \
-          ""Content-Transfer-Encoding: 7bit"" \
-          ""Content-Disposition: inline"" \
-          ""X-Comment: # these headers are all superfluous really"" \
-          ""X-Comment: # (default is text/plain us-ascii 7bit inline)"" \
-          ""X-Comment: # but the next empty line is important"" \
-          """" \
-          ""The reports are attached to this email as requested"" \
-          """"
+          "From: jrpng" \
+          "To: tom@gmail.com" \
+          "Subject: Test new Bash script" \
+          "Mime-Version: 1.0" \
+          "Content-Type: multipart/mixed; boundary=\"$boundary\"" \
+          "X-Comment: # notice the empty line after this one" \
+          "" \
+          "--${boundary}" \
+          "Content-Type: text/plain; charset=\"US-ASCII\"" \
+          "Content-Transfer-Encoding: 7bit" \
+          "Content-Disposition: inline" \
+          "X-Comment: # these headers are all superfluous really" \
+          "X-Comment: # (default is text/plain us-ascii 7bit inline)" \
+          "X-Comment: # but the next empty line is important" \
+          "" \
+          "The reports are attached to this email as requested" \
+          ""
 
-  for file in ""${attachments[@]}""; do
-      [ ! -f ""$file"" ] &&
-          echo ""Attachment $file not found, omitting file""  >&2 && 
+  for file in "${attachments[@]}"; do
+      [ ! -f "$file" ] &&
+          echo "Attachment $file not found, omitting file"  >&2 && 
           continue
-      mimetype=$(get_mimetype ""$file"")
+      mimetype=$(get_mimetype "$file")
       printf '%s\n' \
-          ""--${boundary}"" \
-          ""Content-Type: $mimetype"" \
-          ""Content-Transfer-Encoding: base64"" \
-          ""Content-Disposition: attachment; filename=\""$file\"""" \
-          """"
-      base64 ""$file""
+          "--${boundary}" \
+          "Content-Type: $mimetype" \
+          "Content-Transfer-Encoding: base64" \
+          "Content-Disposition: attachment; filename=\"$file\"" \
+          ""
+      base64 "$file"
       echo
   done
-  printf '%s\n' ""--${boundary}--""
+  printf '%s\n' "--${boundary}--"
 } | /usr/lib/sendmail -t -oi
diff --git a/data/stackoverflow-snippets/bash/770 b/data/stackoverflow-snippets/bash/770
--- a/data/stackoverflow-snippets/bash/770
+++ b/data/stackoverflow-snippets/bash/770
@@ -3,10 +3,10 @@ $1 & # executes a program in background which is provided as an argument
 pid=$! # stores executed process id in pid
 
 # check whether process is still running
-# The ""[^[]"" excludes the grep from finding itself in the ps output
-if ps | grep ""$pid[^[]"" >/dev/null
+# The "[^[]" excludes the grep from finding itself in the ps output
+if ps | grep "$pid[^[]" >/dev/null
 then
-    echo ""success (running)""  # process is still running
+    echo "success (running)"  # process is still running
 else
     # If the process is already terminated, then there are 2 cases:
     # 1) the process executed and stop successfully
@@ -14,9 +14,9 @@ else
 
     if wait $pid # check if process executed successfully or not
     then
-        echo ""success (ran)""
+        echo "success (ran)"
     else
-        echo ""failed (returned $?)"" # process terminated abnormally
+        echo "failed (returned $?)" # process terminated abnormally
     fi
 fi
 
diff --git a/data/stackoverflow-snippets/bash/783 b/data/stackoverflow-snippets/bash/783
--- a/data/stackoverflow-snippets/bash/783
+++ b/data/stackoverflow-snippets/bash/783
@@ -1,14 +1,14 @@
-url=""URL/api/search/dates?dateFields=created&from=${Two_Years_Ago}&today&repos=npm-local-lrn""
+url="URL/api/search/dates?dateFields=created&from=${Two_Years_Ago}&today&repos=npm-local-lrn"
 
-if result=$(curl -s --fail  -u username:password ""$url""); then
-  readarray -t installers < <(jq -r '.results[].uri' <<<""$result"" | sed 's=/api/storage==')
+if result=$(curl -s --fail  -u username:password "$url"); then
+  readarray -t installers < <(jq -r '.results[].uri' <<<"$result" | sed 's=/api/storage==')
   if (( ${#installers[@]} )); then
-    for installer in ""${installers_to_delete[@]}""; do
-      echo ""$installer""
+    for installer in "${installers_to_delete[@]}"; do
+      echo "$installer"
     done
   else
-    echo ""Empty list of installers retrieved"" >&2
+    echo "Empty list of installers retrieved" >&2
   fi
 else
-  echo ""HTTP error retrieving installers"" >&2
+  echo "HTTP error retrieving installers" >&2
 fi
diff --git a/data/stackoverflow-snippets/bash/797 b/data/stackoverflow-snippets/bash/797
--- a/data/stackoverflow-snippets/bash/797
+++ b/data/stackoverflow-snippets/bash/797
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 
 # this code requires bash 4.0 -- fail if run with non-bash or older shell
-if [ -z ""$BASH_VERSION"" ] || [[ $BASH_VERSION = [1-3]* ]]; then
-  echo ""ERROR: Script requires bash 4.0 or newer"" >&2
+if [ -z "$BASH_VERSION" ] || [[ $BASH_VERSION = [1-3]* ]]; then
+  echo "ERROR: Script requires bash 4.0 or newer" >&2
   exit 1
 fi
 
@@ -16,15 +16,15 @@ declare -A parameter_map=(
 args=( )
 for arg; do
   if [[ ${parameter_map[$arg]+exists} ]]; then
-    args+=( ""${parameter_map[$arg]}"" )
+    args+=( "${parameter_map[$arg]}" )
   else
-    args+=( ""$arg"" )
+    args+=( "$arg" )
   fi
 done
 
 # update the script's arguments based on the above
-set -- ""${args[@]}""
+set -- "${args[@]}"
 
 # for test purposes, print all our arguments
-echo ""Arguments as follows:""
-printf ' - %q\n' ""$@""
+echo "Arguments as follows:"
+printf ' - %q\n' "$@"
diff --git a/data/stackoverflow-snippets/bash/809 b/data/stackoverflow-snippets/bash/809
--- a/data/stackoverflow-snippets/bash/809
+++ b/data/stackoverflow-snippets/bash/809
@@ -1,17 +1,17 @@
-test_goodtest () { echo ""OK""; }
-test_badtest () { ! echo ""NOT OK""; }
+test_goodtest () { echo "OK"; }
+test_badtest () { ! echo "NOT OK"; }
 
 run_as_teamcity_test ()
 {
     local name=$1
-    echo ""##teamcity[testStarted name='$name' captureStandardOutput='true']""
-    if ! ""$name""; then
+    echo "##teamcity[testStarted name='$name' captureStandardOutput='true']"
+    if ! "$name"; then
         ANY_TEST_FAILURE=true
-        FAILED_TESTS=""${FAILED_TESTS}    ${name}\n""
-        echo ""##teamcity[testFailed name='$name']""
-        echo -e ""\033[31mTests failed: $name\033[0m""
+        FAILED_TESTS="${FAILED_TESTS}    ${name}\n"
+        echo "##teamcity[testFailed name='$name']"
+        echo -e "\033[31mTests failed: $name\033[0m"
     fi
-    echo ""##teamcity[testFinished name='$name']""
+    echo "##teamcity[testFinished name='$name']"
 }
 
 run_as_teamcity_test test_goodteset
diff --git a/data/stackoverflow-snippets/bash/810 b/data/stackoverflow-snippets/bash/810
--- a/data/stackoverflow-snippets/bash/810
+++ b/data/stackoverflow-snippets/bash/810
@@ -8,8 +8,8 @@ function install_packer_linux() {
 
 
 function check_unzip() {
-  if ! [ -x ""$(command -v unzip)"" ]; then
-    echo ""Error: unzip is not installed""
+  if ! [ -x "$(command -v unzip)" ]; then
+    echo "Error: unzip is not installed"
     return 1
   else
     return 0
@@ -17,8 +17,8 @@ function check_unzip() {
 }
 
 function check_wget() {
-  if ! [ -x ""$(command -v wget)"" ]; then
-    echo ""Error!: wget is not installed""
+  if ! [ -x "$(command -v wget)" ]; then
+    echo "Error!: wget is not installed"
     return 1
   else
     return 0
diff --git a/data/stackoverflow-snippets/bash/840 b/data/stackoverflow-snippets/bash/840
--- a/data/stackoverflow-snippets/bash/840
+++ b/data/stackoverflow-snippets/bash/840
@@ -5,10 +5,10 @@
 set_num_files()
 {
     nfiles=${1:-256}
-    if [ ""$(ulimit -n)"" -ne ""$nfiles"" ]
-    then if ulimit -S -n ""$nfiles"" 
+    if [ "$(ulimit -n)" -ne "$nfiles" ]
+    then if ulimit -S -n "$nfiles" 
          then : OK
-         else echo ""Failed to set num files to $nfiles"" >&2
+         else echo "Failed to set num files to $nfiles" >&2
               ulimit -HSa >&2
               exit 1
          fi
@@ -18,45 +18,45 @@ set_num_files()
 test_python_7000()
 {
     set_num_files 7000
-    timecmd -smr python3 pyscript.py ""$@""
+    timecmd -smr python3 pyscript.py "$@"
 }
 
 test_perl_7000()
 {
     set_num_files 7000
-    timecmd -smr perl jlscript.pl ""$@""
+    timecmd -smr perl jlscript.pl "$@"
 }
 
 test_awk_7000()
 {
     set_num_files 7000
-    AWK=/opt/gnu/bin/awk timecmd -smr sh awkscript.sh ""$@""
+    AWK=/opt/gnu/bin/awk timecmd -smr sh awkscript.sh "$@"
 }
 
 test_awk_256()
 {
     set_num_files 256   # Default setting on macOS 10.13.1 High Sierra
-    AWK=/opt/gnu/bin/awk timecmd -smr sh awkscript-256.sh ""$@""
+    AWK=/opt/gnu/bin/awk timecmd -smr sh awkscript-256.sh "$@"
 }
 
 test_op_shell()
 {
-    timecmd -smr sh opscript.sh ""$@""
+    timecmd -smr sh opscript.sh "$@"
 }
 
 test_jl_shell()
 {
-    timecmd -smr sh jlscript.sh ""$@""
+    timecmd -smr sh jlscript.sh "$@"
 }
 
 test_chepner_1_shell()
 {
-    timecmd -smr bash chepner-1.sh ""$@""
+    timecmd -smr bash chepner-1.sh "$@"
 }
 
 test_chepner_2_shell()
 {
-    timecmd -smr bash chepner-2.sh ""$@""
+    timecmd -smr bash chepner-2.sh "$@"
 }
 
 shopt -s nullglob
@@ -81,7 +81,7 @@ for function in \
     test_python_7000
 do
     mkdir split_DB
-    boxecho ""${function#test_}""
+    boxecho "${function#test_}"
     time $function file
     # Basic validation - the same information should appear for all scripts
     ls split_DB | wc -l
diff --git a/data/stackoverflow-snippets/bash/93 b/data/stackoverflow-snippets/bash/93
--- a/data/stackoverflow-snippets/bash/93
+++ b/data/stackoverflow-snippets/bash/93
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-logfile=""/tmp/logs/mount.log""               # add 1 quote
-timestamp=$( date ""+%Y-%m-%d %H:%M:%S"" )
+logfile="/tmp/logs/mount.log"               # add 1 quote
+timestamp=$( date "+%Y-%m-%d %H:%M:%S" )
 mounts=(
     /reachengine 
     /reachdata/mongo 
@@ -20,11 +20,11 @@ mounts=(
 while sleep 10m; do
     status=$(
         for mnt in ${mounts[@]}; do 
-            mountpoint -q ""$mnt"" || echo ""$timestamp $mnt missing""
+            mountpoint -q "$mnt" || echo "$timestamp $mnt missing"
         done
     )
-    if [ ""$status"" ]; then
-        echo ""$status"" >> $logfile
-        echo ""$status"" | mail -s ""Missing mount"" ####@###.##
+    if [ "$status" ]; then
+        echo "$status" >> $logfile
+        echo "$status" | mail -s "Missing mount" ####@###.##
     fi
 done 
diff --git a/data/stackoverflow-snippets/bash/99 b/data/stackoverflow-snippets/bash/99
--- a/data/stackoverflow-snippets/bash/99
+++ b/data/stackoverflow-snippets/bash/99
@@ -1,12 +1,12 @@
 # Default values:
-flag1=""false""    # Note: ""false"" is just a text string, this is a cheat.
-flag2=""false""    # See note at end.
+flag1="false"    # Note: "false" is just a text string, this is a cheat.
+flag2="false"    # See note at end.
 year=2001
 number=42    # because 42 is the correct default number
 
 # Parse the supplied options
-while getopts ""y:n:12"" OPT; do
-    case ""$OPT"" in
+while getopts "y:n:12" OPT; do
+    case "$OPT" in
         y)
             year=${OPTARG}
             ;;
@@ -14,13 +14,13 @@ while getopts ""y:n:12"" OPT; do
             number=${OPTARG}
             ;;
         1)
-            flag1=""true""
+            flag1="true"
             ;;
         2)
-            flag2=""true""
+            flag2="true"
             ;;
         *)
-            echo ""Usage: $0 [-y year] [-n number] [-1|-2]"" >&2
+            echo "Usage: $0 [-y year] [-n number] [-1|-2]" >&2
             exit 1
             ;;
     esac
@@ -29,6 +29,6 @@ shift $((OPTIND-1))
 
 # Enforce rules about option combos
 if $flag1 && $flag2; then
-    echo ""$0: The options -1 and -2 cannot be specified together."" >&2
+    echo "$0: The options -1 and -2 cannot be specified together." >&2
     exit 1
 fi
diff --git a/data/stackoverflow-snippets/php/131 b/data/stackoverflow-snippets/php/131
--- a/data/stackoverflow-snippets/php/131
+++ b/data/stackoverflow-snippets/php/131
@@ -19,18 +19,18 @@
 #===============================================================================
 
 tmpfile=`mktemp`
-HEADERLINE='<link rel=""stylesheet"" href=""https://test.com/my.css>'
+HEADERLINE='<link rel="stylesheet" href="https://test.com/my.css>'
 
 function error()
 {
-    echo ""*** ERROR:"" $*
+    echo "*** ERROR:" $*
     exit 1
 }
 
 for f in *.html ; do 
-    if ! head -n 1 $f | grep -q ""$HEADERLINE"" ; then
+    if ! head -n 1 $f | grep -q "$HEADERLINE" ; then
         echo adding header to $f
-        echo ""$HEADERLINE"" > $tmpfile
+        echo "$HEADERLINE" > $tmpfile
         cat $f >> $tmpfile || error reading $f
         cp $tmpfile $f || error writing $f
     fi
